Repository 4ndresdev/pomo.app, pull requests merged in 2025-01, with the labels that each got.

#75 Components performance
  src/components/timer/Timer.jsx
  src/components/timer/TimerControls.jsx
  src/components/timer/TimerDisplay.jsx
Labels: enhancement

#77 Add Timer context features and integrate confetti effect on timer completion
  jsconfig.json
  package-lock.json
  package.json
  src/components/timer/Timer.jsx
  src/components/timer/TimerControls.jsx
  src/components/timer/TimerDisplay.jsx
  src/contexts/TimerContext.jsx
  src/utils/confetti.js
  vite.config.js
Labels: enhancement

#78 Random motivational phrases function logic
  src/components/timer/Timer.jsx
  src/constants/motivationalPhrasesEnglish.js
  src/constants/motivationalPhrasesSpanish.js
  src/utils/getRandomPhrase.js
Labels: enhancement

#80 Refactor Timer component to use useMemo for motivational phrase generation
  src/components/timer/Timer.jsx
Labels: bug

#81 Replace NextUI components with HeroUI equivalents and add AlertConfirm component for confirmation dialogs
  package-lock.json
  package.json
  src/components/profile/Profile.jsx
  src/components/steps/ProfileStep.jsx
  src/components/steps/WallpaperStep.jsx
  src/components/timer/Timer.jsx
  src/components/ui/AlertConfirm.jsx
  src/components/ui/ButtonWithIcon.jsx
  src/components/ui/FireDay.jsx
  src/contexts/TimerContext.jsx
  src/main.jsx
  src/pages/Onboarding.jsx
  tailwind.config.js
Labels: enhancement

#82 Implement new feature for user profile customization options
  package-lock.json
Labels: enhancement

#83 remove package.lock
  package-lock.json
Labels: enhancement

#86 Refactor timer context and UI components; update dependencies and improve confetti animation
  package-lock.json
  package.json
  src/assets/sounds/checkedSound.mp3
  src/assets/sounds/completedSound.mp3
  src/components/timer/Timer.jsx
  src/components/ui/AlertConfirm.jsx
  src/contexts/TimerContext.jsx
  src/utils/confetti.js
Labels: Task

#87 Schema creation and rxdb configuration
  package-lock.json
  package.json
  src/schemas/progress.schema.js
  src/schemas/task.schema.js
  src/schemas/user.schema.js
  src/services/db.js
Labels: enhancement

#88 db file refactoring and creation of user db file
  src/App.jsx
  src/hooks/useNameStep.js
  src/schemas/user.schema.js
  src/services/db.js
  src/services/db/user.db.js
Labels: enhancement

#89 Finish rxdb implementation
  package-lock.json
  package.json
  src/components/profile/Profile.jsx
  src/components/timer/Timer.jsx
  src/components/ui/Loading.jsx
  src/constants/styleConstants.js
  src/contexts/OnboardingContext.jsx
  src/contexts/TimerContext.jsx
  src/hooks/useCloudinary.js
  src/hooks/useProfileStep.js
  src/hooks/useWallpaperStep.js
  src/pages/Dashboard.jsx
  src/pages/Onboarding.jsx
  src/router/PrivateRoutes.jsx
  src/router/PublicRoutes.jsx
  src/services/db/user.db.js
  src/utils/wait.js
Labels: enhancement

#90 Finish rxdb implementation
  src/services/db.js
Labels: enhancement

#91 context timer optimization
  src/contexts/TimerContext.jsx
Labels: enhancement
